spring.application.name=GitHub-Activity-CLI

spring.datasource.url=jdbc:h2:file:C:/Users/91949/Desktop/Java Development/GitHub-Activity-CLI/GitHubUserData
spring.h2.console.enabled=true
#spring.sql.init.mode=always
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.sql.init.schema-locations=classpath:sql/userdata_schema.sql
spring.jpa.hibernate.ddl-auto=update